name: celloracle_web_app_hourly_test

on:
  schedule:
    - cron: '16 * * * *'

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: test celloracle web
        run: |
            python --version
            ls
            python check_celloracle_webapp_status.py

