name: celloracle_web_app_hourly_test

on:
  schedule:
    - cron: '57 * * * *'
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    timeout-minutes: 60    
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda, install packages, and test celloracle
        run: |
            python --version
            ls
            python check_celloracle_webapp_status.py# command to run tests

